
variables = {
    1:'Temp Pokemon Choice',
    2:'Temp Move Choice',
    3:'Temp Pokemon Name',
    4:'Temp Move Name',
    5:'Temp Text Entry',
    6:'Poké Center healing ball count',
    7:'Starter choice',
    8:'Apricorn being converted',
    9:'Fossil being revived',
    10:'Elevator current floor',
    11:'Elevator new floor',
    12:'Rival name',
    13:'E4 defeated count'
}

switches = {
    1:'Starting over',
    2:'Seen Pokérus in Poké Center',
    3:'Choosing starter',
    4:'Defeated Gym 1',
    5:'Defeated Gym 2',
    6:'Defeated Gym 3',
    7:'Defeated Gym 4',
    8:'Defeated Gym 5',
    9:'Defeated Gym 6',
    10:'Defeated Gym 7',
    11:'Defeated Gym 8',
    12:'Defeated Elite Four',
    13:'Fossil revival in progress',
    14:'isDay',
    15:'isNight',
    16:'isMorning',
    17:'isAfternoon',
    18:'isEvening',
    19:'isWeekday',
    20:'isNotWeekday',
    21:'isSSon("A")',
    22:'isSSoff("A")',
    23:'s:cooledDown?(86400)',
    24:'s:cooledDownDays?(1)',
    25:'s:pbInSafari?',
    26:'s:pbBugContestUndecided?',
    27:'s:pbBugContestDecided?',
    28:'s:pbInChallenge?',
    29:'Has National Dex',
    30:'s:pbNextMysteryGiftID>0',
    31:'Shiny wild Pokémon',
    32:'Fateful encounters',
    33:'No money lost in battle',
    34:'No Mega Evolution',
    51:'Visited Berth Island',
    52:'Visited Faraday Island',
    53:'Latias/Latios roaming',
    54:'Kyogre roaming',
    55:'Entei roaming',
    56:'Reset Mew encounter',
    57:'Boulder down hole rock cave',
    58:'Boulder down hole ice cave'
}